### ISSUE TITLE
Type issue with `Router` children

### ISSUE THREAD

**Issue by rschristian** [preactjs/preact-iso#15]
```jsx
<Router>
    {['/', '/foo'].map((r) => (
        <Route path={r} component={Example} />
    ))}
    <Route path="/bar" component={Example} />
</Router>
```

This should be valid but the expression returns the following error:

```
Type 'Element[]' is missing the following properties from type 'VNode<{}>': type, props, key(2739)
```

(Weirdly enough, without the additional `<Route>`, no error is returned at all)

[`Route` returns a `VNode`](https://github.com/preactjs/preact-iso/blob/bf7169380485435e87d537c965a58c822f97fb2a/src/router.d.ts#L35), not quite sure how in the world that becomes an `Element[]`. Expanding the children type to be a union of `VNode[] | JSXInternal.Element[]` allows for some invalid children that will break routing, so that's seemingly a no-go.

Not quite sure what the correct type is meant to be here.

**Comment by zetaraku** [comment]
You should destructure the mapped array otherwise there will be a nested array in the `VNode[]`:

```tsx
<Router>
    {...['/', '/foo'].map((r) => (
        <Route path={r} component={Example} />
    ))}
    <Route path="/bar" component={Example} />
</Router>
```

**Comment by rschristian** [comment]
> You should destructure the mapped array otherwise there will be a nested array in the VNode[]:

Passing an array of children is completely valid. Or should be, rather.

**Comment by zetaraku** [comment]
> Passing an array of children is completely valid. Or should be, rather.

Yes, passing an array of children is completely valid.

However, the [implementation](https://github.com/preactjs/preact/blob/eb3767723d43e8a38453efc28d187810edfa4231/src/create-element.js#L26-L29) of `createElement()` wraps children into a single array **when there is more than one**.

So,

```tsx
<Router>
    <Route path="/" component={Example} />
    <Route path="/foo" component={Example} />
    <Route path="/bar" component={Example} />
</Router>
```

is equivalent to:

```tsx
<Router>
    {[
        <Route path="/" component={Example} />,
        <Route path="/foo" component={Example} />,
        <Route path="/bar" component={Example} />,
    ]}
</Router>
```

whereas, in your case,

```tsx
<Router>
    {['/', '/foo'].map((r) => (
        <Route path={r} component={Example} />
    ))}
    <Route path="/bar" component={Example} />
</Router>
```

is actually equivalent to:

```tsx
<Router>
    {[
        [
            <Route path="/" component={Example} />,
            <Route path="/foo" component={Example} />,
        ],
        <Route path="/bar" component={Example} />,
    ]}
</Router>
```

`VNode` is just another name of `JSX.Element` in the Preact world.

The problem is that you are nesting an array in another array.

**Comment by rschristian** [comment]
...you might want to take a peek at my GH profile, I'm very well aware of what Preact does and how it works here 😅

This was an issue opened on behalf of user, and for types -- I certainly don't need someone to explain Preact internals.

If you have a solution for the types, then great! I'd love to see a PR.

**Comment by zetaraku** [comment]
Sorry, I didn't expect that the `Router` can accept nested children of any depth (That's surprising for me 😅)

I'll try to figure out this one :)
