### ISSUE TITLE
Micro frontend (SSR + selective / partial rendering) with Bun

### ISSUE THREAD

**Issue by baptistecs** [preactjs/preact-iso#18]
Hi,

I am looking for a documentation / example in order to do SSR + selective / partial rendering using Bun + Typescript + Preact + Preact-ISO + multi pages app.

I managed to do both SSR and non pre-rendered components but I don't manage to do both at the same time.

More explicitly, I would like to have 2 builds from the same application + components:
- One to generate one static HTML file per page and add a container for the menu in the Menu component if built for SSR (e.g. `<div id="menu-app"><!-- pre rendered menu --></div>`)
- One to generate a commonJS (or an ESM module) extension which will be loaded from my static files and generate the menu dynamically and display new links if the user is authenticated for example).

I found a few things, but nothing helpful for a multi page app using Preact-ISO.

I would really appreciate any help 🙇‍♂️ 

There is the Bun command to initiate the project:
```shell
bun create preact <name of app>
```

**Comment by rschristian** [comment]
"Partial rendering", as in [islands](https://jasonformat.com/islands-architecture)?

There's a couple islands plugins out there for Vite, I can recommend [`@barelyhuman/preact-island-plugins`](https://github.com/barelyhuman/preact-island-plugins), but this isn't in the scope of `preact-iso` really.

**Comment by baptistecs** [comment]
@rschristian yes, that’s exactly it, thanks a lot! :)
