### ISSUE TITLE
`LocationProvider` isn't used in all examples, making it unclear that it's required

### ISSUE THREAD

**Issue by donkeyDau** [preactjs/preact-iso#23]
I try to switch from `preact-router` to `preact-iso` but I'm already failing at the simplest implementation.

I have a minimal working example:

```Javascript
import { h, render } from 'preact';
import { lazy, Router } from 'preact-iso';

const HelloWorld = lazy(() => import('./HelloWorld.js'));

const AppWrapper = () => {
  return (
    <Router>
      <HelloWorld path="/" />
    </Router>
  );
};

render(<AppWrapper />, document.body);
```

Crashes with:

> Uncaught TypeError: A is undefined
>     Preact 38
>     <anonymous> index.js:63
> router.js:42:1
>     Preact 2
>     some self-hosted:137
>     Preact 36
>     <anonymous> index.js:63

Looking at the [exec function](https://github.com/preactjs/preact-iso/blob/main/src/router.js#L41) I assume that the passed `url` is undefined as the `RouteContext` is just an empty object. Maybe I'm missing something fundamental here ...

**Comment by rschristian** [comment]
You need to wrapper your `<Router>` in a `<LocationProvider>`

**Comment by donkeyDau** [comment]
Seems legit. Should have seen it in the Readme. Thank you!

**Comment by rschristian** [comment]
In all fairness this is missing from some of the ReadMe examples where the router itself isn't the "key piece", if you will. Standardizing/making this consistent is something we need to address, along with other doc improvements.

As such, I'm going to re-open this w/ a slight rename as I do think it's a very valid issue that we don't make clear enough.

**Comment by donkeyDau** [comment]
I for my side rely mainly on docs. Checking types is an extra step which I'm taking if the docs are not clear enough. So a (tabular) overview what's available makes it quite easy for me to get the full scope of the package and whether it fits my needs or not.

Also the types are not given much hint why this was implemented and what it is useful for. E.g. what's the favor in using `useRoute` instead of the props passed by the Router into my component? Or the props: what is the `default` for on the Route? One can assume but needs to give it try to verify.

**Comment by rschristian** [comment]
> I for my side rely mainly on docs. Checking types is an extra step which I'm taking if the docs are not clear enough.

I completely get that, but the best I can do for the moment is to point to them.

Preact is entirely maintained by volunteers with limited time, we all have jobs and lives outside of this. I can't guarantee the docs will be updated shortly, so with that in mind, I'd recommend using the types as reference even if it's not your preference.

**Comment by donkeyDau** [comment]
> Preact is entirely maintained by volunteers with limited time, we all have jobs and lives outside of this. I can't guarantee the docs will be updated shortly, so with that in mind, I'd recommend using the types as reference even if it's not your preference.

I'm completely aware of that and I'm very grateful for that! I'm sorry if I gave the impression that I was demanding something. I just wanted to point out what made it difficult for me to start using this library.
