### ISSUE TITLE
Preact-iso library conflicts with i18next library

### ISSUE THREAD

**Issue by kamenomi-dev** [preactjs/preact-iso#29]
> [!NOTE]
> This issue is translated by Google Translate.

I tried to use the Preact-iso library in combination with the i18next library, but when getting the language file it automatically jumps to the homepage.

screenshot:

> Screenshots · Original language files

![image](https://github.com/preactjs/preact-iso/assets/77380048/bf92c894-87ba-41f0-9ee3-ca6c9dd81fd6)

> Screenshots · Actual running results

![image](https://github.com/preactjs/preact-iso/assets/77380048/3cb0d1f1-c434-4c58-ae68-80cdb615008f)

![image](https://github.com/preactjs/preact-iso/assets/77380048/cdf16e68-3004-40f3-af1b-127dae548831)

> Screenshots · Related code

![image](https://github.com/preactjs/preact-iso/assets/77380048/e7693527-3668-4b00-8ae1-7f76b0e53d62)

![image](https://github.com/preactjs/preact-iso/assets/77380048/3edab095-99bf-4e19-95ff-0f10cb22576f)

**Comment by rschristian** [comment]
We need a _minimal_ reproduction, not screenshots.

Please make a StackBlitz or CodeSandbox repro, or link to a GitHub repo.

**Comment by kamenomi-dev** [comment]
https://codesandbox.io/p/devbox/musing-worker-vm7qww?file=%2Fsrc%2Fapp.tsx%3A9%2C6&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxum1dmc00053j6j31vep2nx%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxum1dmb00023j6jt2sczm7a%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxum1dmb00033j6jvucd0dyi%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxum1dmb00043j6jidb52tq1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxum1dmb00023j6jt2sczm7a%2522%253A%257B%2522id%2522%253A%2522clxum1dmb00023j6jt2sczm7a%2522%252C%2522activeTabId%2522%253A%2522clxumm5j600023j6k048hmhnq%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxum1dma00013j6jab2ppr6n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clxumcllf011f3j6j7i1rwkpc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxumm5j600023j6k048hmhnq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A9%252C%2522startColumn%2522%253A6%252C%2522endLineNumber%2522%253A9%252C%2522endColumn%2522%253A6%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fapp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clxum1dmb00043j6jidb52tq1%2522%253A%257B%2522id%2522%253A%2522clxum1dmb00043j6jidb52tq1%2522%252C%2522activeTabId%2522%253A%2522clxumao5r00y83j6jusu7knqa%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clxumao5r00y83j6jusu7knqa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clxum1dmb00033j6jvucd0dyi%2522%253A%257B%2522id%2522%253A%2522clxum1dmb00033j6jvucd0dyi%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clxum1o7i00273j6j14c0cu4l%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clxum1o7i00273j6j14c0cu4l%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by rschristian** [comment]
Thanks, but this doesn't look to be related to `preact-iso` at all. This also fails:

```js
import { render } from 'preact';

import i18n, { t } from 'i18next';
import Backend from 'i18next-http-backend';
import LanguageDetector from 'i18next-browser-languagedetector';
import { initReactI18next } from 'react-i18next';

i18n
  .use(Backend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    backend: {
      cleanCode: true,
      loadPath: '/langs/{{lng}}.json',
    },
    interpolation: {
      escapeValue: false, // react already safes from xss
    },
  });

function App() {
    return <p>{t('test', 'failure to translate')}</p>
}

render(<App />, document.getElementById('app'));
```

I'm not familiar with `i18next`, but it's likely you've misconfigured something.

**Comment by rschristian** [comment]
If you can provide information on how this is related to `preact-iso`, we can reopen and take another look.
