### ISSUE TITLE
Blocking a route change

### ISSUE THREAD

**Issue by n04y** [preactjs/preact-iso#31]
I would like to block route changes under some condition, for example when then user has entered data that has not yet been saved.
For plain HTML/JS there is `window.addEventListener("beforeunload", e => { if (condition) e.preventDefault() })`.
However, I don't see a way to block route changes in this library yet.
It would be cool to have something like
```js
<Router canRoute={e => someCallbackReturningABoolean(e)}>
    ...
</Router>
```

Is there currently a way to achieve this or is this planned to be implemented?
Thanks in advance!

**Comment by rschristian** [comment]
Add an event listener for intercepting `'click'` and `'popstate'` events, blocking them if your user has unsaved work.

**Comment by rschristian** [comment]
Yup, something along these lines would be the recommendation.
