### ISSUE TITLE
Router typings incompatible with class components

### ISSUE THREAD

**Issue by foxt** [preactjs/preact-iso#35]
```ts
<Router>
    {/* Type 'typeof ClassComponent' is not assignable to type 'AnyComponent<{ path: string; component: typeof ClassComponent; }> & (typeof ClassComponent | undefined)'. */}
    <Route path="/class" component={ClassComponent} />
    {/* works ok */}
    <Route path="/fc" component={FunctionComponent} />
</Router>
```

It works at runtime, but the typing has an error.

**Comment by rschristian** [comment]
I'm not entirely sure that's an issue here at the moment -- I thought `AnyComponent` (from `preact` itself) was meant to include class components.

Will need to double check.

**Comment by rschristian** [comment]
Found the issue, but _I think_ this should be corrected upstream. If you're willing to patch (`patch-package` or `pnpm patch` are great for this sort of thing), you can do this:

```diff
 // node_modules/preact/src/index.d.ts
 export type AnyComponent<P = {}, S = {}> =
     | FunctionComponent<P>
-    | Component<P, S>;
+    | ComponentConstructor<Props, S>;
```
