### ISSUE TITLE
Error thrown upon clicking any non-link

### ISSUE THREAD

**Issue by tomjw64** [preactjs/preact-iso#46]
Upon switching to preact-iso from preact-router my app now throws an error anytime a click occurs on any non-anchor element:
![Screenshot from 2024-10-19 21-04-21](https://github.com/user-attachments/assets/5a8f4843-e4d7-40b6-92dc-12384b83cf9a)

I believe it's a result of not checking for null [here](https://github.com/preactjs/preact-iso/pull/42/files#diff-d7f41ba1aa74f41ef4b0c2337abe593d08092ffae6528a8aa2db712afeee0b66R19-R20) in [this recent PR](https://github.com/preactjs/preact-iso/pull/42)

**Comment by rschristian** [comment]
Crap, good spot.

**Comment by rschristian** [comment]
Fix released in v2.8.1
