### ISSUE TITLE
programmatically redirect to another route using `route` method is missing from `preact-iso`.

### ISSUE THREAD

**Issue by OurCodeBase** [preactjs/preact-iso#53]
Hello @robertknight 

I cannot find any way to programmatically redirect to another route using `route` function, which is present in `preact-router`.

**Comment by rschristian** [comment]
I assume you meant to tag me, not Robert, but `route` exists upon the `useLocation` hook: https://github.com/preactjs/preact-iso?tab=readme-ov-file#uselocation

```jsx
import { useLocation } from 'preact-iso';

function MyComponent() {
    const { route } = useLocation();

    route('/foo');
}
```

**Comment by OurCodeBase** [comment]
Thanks `@rschristian `

You've resolved my issue 👍
I'm going to close this issue.
